### ISSUE TITLE
Build for Windows

### ISSUE THREAD

**Issue by mkanev** [luben/zstd-jni#2]
How long would it take to supply /windows_8.1/amd64 build with the library? Or where to find instructions how to build it myself?

**Comment by luben** [comment]
Hi,
The build instructions are in the README:

https://github.com/luben/zstd-jni#building-and-dependencies

All you will need is JDK and SBT. Here is how to install sbt on windows.
http://www.scala-sbt.org/0.13/docs/Installing-sbt-on-Windows.html

The rest is "sbt compile package publish-local"

If you know some hosts providing ssh access to windows that I can use for compilation I may include it the pre-build packages for the next version

**Comment by mkanev** [comment]
Might be closed with PR #5

**Comment by luben** [comment]
Hi,

I made it build and pass the tests on both win32 and win64 (after a lot of trials and errors):

https://ci.appveyor.com/project/luben/zstd-jni/build/22

The only step left is uploading the result and making a new release may be tomorrow.

**Comment by luben** [comment]
The release with windows support (x86 and amd64) is on maven central, can you try it?

**Comment by mkane007** [comment]
@luben checked the JAR file. Windows build missed.

**Comment by mkane007** [comment]
Also make sure to get the latest version of `sbt-jni` plugin - they had have issues with windows too.

**Comment by luben** [comment]
@mkane007 are you sure you are not using an old jar? When I look into the jar here:
http://repo1.maven.org/maven2/com/github/luben/zstd-jni/0.5.0/zstd-jni-0.5.0.jar
I see both win/x86 and win/amd64 dlls inside. Also I have changed the logic where to look for the windows dlls.

Please try again. It may be also maven-central being slow on updating its index.

**Comment by mkane007** [comment]
@luben you're right. Was looking at different repository. Thanks.

**Comment by luben** [comment]
Thanks for the pointer to the new version of the sbt-jni. It has some other problems compiling on windows so I have overriden some of its logic in my build:

- one of the problems is that the jni_md.h provided from the windows JDK is compatible only with visual studio (uses __int64) and does not work with msys/gcc so I have put fixed version in my repo (using inttypes.h and int64_t)

- another problem is that jni dlls compiled on windows (with gcc and I suppose other compilers) needs extra flags for the linker and the compiler, e.g. "--kill-at" to the linker in order to strip the stdcall suffixes from the symbols (on x86 at least).

BTW, if it now works for you let's close the issue.

**Comment by luben** [comment]
Closing, if it is still a problem, please reopen
