### ISSUE TITLE
UnsatisfiedLinkError: Zstd.frameHeaderSizeMin

### ISSUE THREAD

**Issue by shollander** [luben/zstd-jni#204]
When calling `Zstd.frameHeaderSizeMin()` I receive the following exception:
```
java.lang.UnsatisfiedLinkError: 'int com.github.luben.zstd.Zstd.frameHeaderSizeMin()'
        at com.github.luben.zstd.Zstd.frameHeaderSizeMin(NativeMethod)
        ...
```

**Comment by luben** [comment]
Hmm, looks we lost it in some of the changes of the underlying native library. Currently it is masked as "unstable" and it's not a one number anymore due to support of `magicless` frames: https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L1111-L1124

I think the right approach is to stop exposing it.

What is your use-case?

**Comment by shollander** [comment]
I was attempting to use it in a utility that attempts to recover data from corrupted zstd files.
At the moment I am just using my own numbers from the zstd documentation.

**Comment by luben** [comment]
Make sense for those cases. Though I don't think it's worth exposing it from the java library.
