### ISSUE TITLE
SSE2 support in binaries

### ISSUE THREAD

**Issue by hc-codersatlas** [luben/zstd-jni#88]
Hi, is it possible to build with gcc that has sse2 support? Most if not all Windows / Linux / Mac x64 based machines should be SSE2 compatible (it's literally a requirement of x64). This might speed up the binaries a bit. Thanks!

**Comment by luben** [comment]
It should be possible but not trivial. Currently I am building it on a very old Debian system in order to keep the minimal system requirements for Libc to 2.2.5 - that is needed for all our enterprise friends still running on RHEL5 and our cool new friend that run containers on Apline linux with Musl. So the compiler is also quite old.

May me it will be possible to find another environment that can serve both requirements - newer compiler and restricted libc.

**Comment by luben** [comment]
I have released v1.3.8-4 compiled with gcc-8.2 on linux/amd64. Unfortunately I couldn't make the dynamic BMI2 work but it should be better than the previous releases.
